#%RAML 1.0 Trait
  headers:
    client_id:
      description: Unique identifier assigned to each consuming app for authentication
      type: string
      required: true
    client_secret:
      description: Client secret sent by consuming app for authentication
      type: string
      required: true