#%RAML 1.0 DataType
  type: object
  properties:
    dangerousGoodsHazardousCode?: string
    dangerousGoodsIndicator?: string
    dangerousGoodsMarginNumber?: string
    dangerousGoodsPackingGroup?: string
    dangerousGoodsRegulationCode?: string
    dangerousGoodsShippingName?: string
    dangerousGoodsTechnicalName?: string
    departmentOfTransportationDangerousGoodsNumberHl?: string
    materialSafetyDataSheetNumber?: string
    unDangerousGoodsNumber?: string
    groundTransportationHazardCode?: string
    hazardousAgencyIndicator?: string
    hazardousClassDescription?: string
    hazardousGoodsSubClass?: string
    hazardousOshaClassCode?: string
    hazardousProductDotException?: string
    hazardousReportableQuantityIndicator?: string
    hazardousResponseGuide?: string
    hazardousUom?: string
    hazmatQuestioner?: string