#%RAML 1.0 DataType
  type: object
  properties:
    apnMappingRecords?:
      type: array
      items: !include apnMappingRecords.raml
    vendorRecord?: !include vendorRecord.raml
    brandRecord?: !include brandRecord.raml
    childNutritionLabelRecords?:
      type: array
      items: !include childNutritionLabelRecords.raml
    claimRecords?:
      type: array
      items: !include claimRecords.raml  
    nutrientRecords?:
      type: array
      items: !include nutrientRecords.raml  
    pimGroupRecord?: !include pimGroupRecord.raml
    productContentManagementRecord?: !include productContentManagementRecord.raml
    taxRecord?: !include taxRecord.raml
    hazmatRecord?: !include hazmatRecord.raml
    state?: string
    gtin?: string
    glnOfInformationProvider?: string
    targetMarketCountryCode?: string
    manufacturerProductNumber?: string
    barCodeType?: string
    canceledDate?: string
    consumerAvailabilityDateTime?: string
    countryOfOrigin?: string
    couponFamilyCode?: string
    degreeOfOriginalWortFmcg?: string
    deliveryMethodIndicator?: string
    deliveryToMarketTemperatureMaximum?: string
    deliveryToMarketTemperatureMinimum?: string
    salesPackDepth?: string
    productDescriptionLaptop?: string
    descriptiveSize?: string
    diameter?: string
    discontinuedDate?: string
    drainedWeight?: string
    pimAddDate?: string
    endAvailabilityDateTime?: string
    fatPercentageInDryMatterFmcg?: string
    flashPointTemperature?: string
    functionalName?: string
    fmcgIdentificationNumber?: string
    fmcgIdentificationType?: string
    glnOfBrandOwner?: string
    glnOfContentOwner?: string
    glnOfManufacturer?: string
    glnOfPartiesReceivingPrivateData?: string
    glnOfRepresentingParty?: string
    glnOfSourceDataPool?: string
    gpcCode?: string
    grossWeight?: string
    harmonizedTariffSystemIdentificationCodeHl?: string
    hasBatchNumber?: string
    salesPackHeight?: string
    productDescriptionCustomerProprietary?: string
    isBarCodeSymbologyDerivable?: string
    isItemAConsumerUnit?: string
    isItemADispatchUnitShipping?: string
    catchWeightItem?: string
    isItemAnInvoiceUnit?: string
    isItemAnOrderableUnit?: string
    isNonSoldTradeItemReturnable?: string
    isPackagingMarkedAsRecyclable?: string
    isPackagingMarkedReturnable?: string
    isPackagingMarkedWithExpirationDate?: string
    isPackagingMarkedWithGreenDot?: string
    isPackagingMarkedWithIngredients?: string
    isReload?: string
    isUpcDerivableFromGtin?: string
    isbnNumberFMCG?: string
    issnNumberFMCG?: string
    linearUnits?: string
    nameOfInformationProvider?: string
    manufacturerName?: string
    nameOfSourceDataPool?: string
    nestingIncrementHl?: string
    netContent?: string
    netContentUom?: string
    netWeight?: string
    orderQuantityMaximum?: string
    orderQuantityMinimum?: string
    orderQuantityMultiple?: string
    orderSizingFactor?: string
    orderSizingFactorUom?: string
    orderingLeadTime?: string
    orderingUomHl?: string
    outOfBoxDepthHl?: string
    outOfBoxHeightHl?: string
    outOfBoxWidthHl?: string
    packagingMaterialCode?: string
    packagingMaterialCodeListMaintenanceAgency?: string
    packagingMaterialCompositionQuantity?: string
    packagingMaterialCompositionUom?: string
    packagingTermsAndConditions?: string
    packagingTypeCode?: string
    palletTermsAndConditions?: string
    palletTypeCode?: string
    pegHorizontal?: string
    pegVertical?: string
    piecesPerTradeItemHl?: string
    productRange?: string
    publicationDate?: string
    quantityOfChildren?: string
    quantityOfCompleteLayersContainedInATradeItem?: string
    quantityOfInnerPack?: string
    quantityOfLayersPerPallet?: string
    quantityOfNextLevelTradeItemWithinInnerPack?: string
    quantityOfTradeItemsContainedInACompleteLayer?: string
    quantityOfTradeItemsPerPallet?: string
    quantityOfTradeItemsPerPalletLayer?: string
    replacedTradeItemGtin?: string
    retailPriceOnTradeItem?: string
    sellingUomHl?: string
    sizeCodeListAgency?: string
    sizeCodeValue?: string
    stackingFactor?: string
    stackingWeightMaximum?: string
    startAvailabiltyDateTime?: string
    storageHandlingTemperatureMinimum?: string
    storageHandlingTemperatureMaximum?: string
    subBrand?: string
    suggestedRetailPrice?: string
    targetMarketSubdivisionCode?: string
    temperatureUom?: string
    totalQuantityOfNextLowerLevelTradeItem?: string
    tradeItemFinishDescriptionHl?: string
    tradeItemFormDescription?: string
    tradeItemIdentificationOfNextLowerTradeItem?: string
    tradeItemImportClassificationType?: string
    tradeItemImportClassificationValue?: string
    salesUom?: string
    upcCode?: string
    upcType?: string
    urlForWarrantyHl?: string
    variant?: string
    volume?: string
    volumeUnits?: string
    warrantyDescriptionHl?: string
    weightUnits?: string
    salesPackWidth?: string
    alertNoticeDays?: string
    attributeType1?: string
    attributeType10?: string
    attributeType2?: string
    attributeType3?: string
    attributeType4?: string
    attributeType5?: string
    attributeType6?: string
    attributeType7?: string
    attributeType8?: string
    attributeType9?: string
    attributeValue1?: string
    attributeValue10?: string
    attributeValue2?: string
    attributeValue3?: string
    attributeValue4?: string
    attributeValue5?: string
    attributeValue6?: string
    attributeValue7?: string
    attributeValue8?: string
    attributeValue9?: string
    attributeValueAddType1?: string
    attributeValueAddType2?: string
    attributeValueAddValue1?: string
    attributeValueAddValue2?: string
    caseImage?: string
    commodityProductIndicator?: string
    compositeImage?: string
    ediblePercent?: string
    expirationCodeBasis?: string
    handlingInstructionsText?: string
    headquartersFamilyGroup?: string
    ifdaManufacturerId?: string
    ifdaManufacturerProductNumber?: string
    innerPackQuantity?: string
    itemImage?: string
    lowestLevelProductHierarchyDerivedPackSize?: string
    manufacturerHi?: string
    manufacturerMinorityCode?: string
    manufacturerMinorityCodeDescription?: string
    manufacturerNumber?: string
    manufacturerTi?: string
    masterPackQuantity?: string
    materialSafetyDataSheet?: string
    moistureLoss?: string
    nutritionalUpdateDate?: string
    operatorComments?: string
    picturePath?: string
    pimGroupId?: string
    productMasterNumber?: string
    productDescriptionPsysMainframe?: string
    cashAndCarryEligible?: string
    retailUpc?: string
    productDescriptionUsf?: string
    productSegmentationEffectiveDate?: string
    productSegmentationLevelOne?: string
    productSegmentationLevelThree?: string
    productSegmentationLevelTwo?: string
    productStatus?: string
    purchasePackDepth?: string
    purchasePackHeight?: string
    purchasingPackSizeDescription?: string
    purchasePackUom?: string
    purchasePackWidth?: string
    quantityOfPortions?: string
    quantityOfPortionsUom?: string
    quantityOfSecondLevelInnerPack?: string
    recommendedServingSize?: string
    replacedBy?: string
    salesPackSizeLong?: string
    salesPackSizeShort?: string
    servingSize?: string
    servingSizeType?: string
    servingSizeUom?: string
    servingSuggestions?: string
    shelfLife?: string
    shelfLifeUom?: string
    smallestSalesPackQuantity?: string
    smallestSalesPackUsfProductNumber?: string
    smallestSalesPackUnit?: string
    sourceUsfStandardProductCode?: string
    specSheet?: string
    tradeItemIdentificationType?: string
    tradeItemVolumeFromVendor?: string
    usaEstIdNum?: string
    usfDangerousGoodsCode?: string
    usfNetContent?: string
    usfProductNumber?: string
    vendorDiscontinuedDate?: string
    vendorSpecifiedMaximumStackablePallets?: string
    vendorSpecifiedMaximumStackableTiers?: string
    vendorSpecifiedPalletSize?: string
    weightDensity?: string
    marketingImage?: string
    modificationType?: string
    recommendedServingSizeUom?: string
    replacementUsfProductNumber?: string
    approvedManufacturers?: string
    productCodeOnBol?: string
    productCodePrinting?: string
    productCodeType?: string
    meatBuyersGuideNumber?: string
    imageAvailabilityIndicator?: string
    beefGrade?: string
    hqFamilyClassId?: string
    laptopDesc?: string
    categoryManagerNetworkId?: string
    categoryVpNetworkId?: string
    lastUpdateDate?: string
    nutrientIngredients?: string
    cataloguePrice?: string
    cataloguePriceEffectiveEndDate?: string
    cataloguePriceEffectiveStartDate?: string
    colorCodeListAgency?: string
    colorCodeValue?: string
    colorDescription?: string
    genericIngredient?: string
    genericIngredientStrength?: string
    handlingInstructionsCode?: string
    ingredientStrength?: string
    isNetContentDeclarationIndicated?: string
    minimumTradeItemLifespanFromTimeOfArrival?: string
    modelNumberHl?: string
    returnGoodsPolicyHl?: string
    securityTagLocationHl?: string
    tradeItemGroupIdentificationCode?: string
    tradeItemGroupIdentificationDescription?: string
    biotinRdv?: string
    bwWorflowId?: string
    carbsOtherRdv?: string
    copperRdv?: string
    footnoteRdvPercentage?: string
    iodineRdv?: string
    insolubleFiberRdv?: string
    magnesiumRdv?: string
    monunsaturatedFatRdv?: string
    niacinRdv?: string
    polyunsaturatedFatRdv?: string
    pantothenicRdv?: string
    phosphorousRdv?: string
    potassiumRdv?: string
    riboflavinRdv?: string
    servingPerTradeItem?: string
    solubleFiberRdv?: string
    sugarAlocholRdv?: string
    thiaminRdv?: string
    totalSugarRdv?: string
    vitaminB12Rdv?: string
    vitaminB6Rdv?: string
    vitaminDRdv?: string
    vitaminERdv?: string
    vitaminKRdv?: string
    zincRdv?: string
    division?: string
    exclusiveBrand?: string
    priorityIndicator?: string
    categoryManagerName?: string
    categoryVpName?: string
    juicepct?: string
    productUpdateIndicator?: string
    brandAbbrevPsys?: string
    psysStrorageCode?: string
    isIngredientIrradiatedFmcg?: string
    isRawMaterialIrradiatedFmcg?: string
    isTradeItemIrradiatedFmcg?: string
    isTradeItemRecalledHl?: string
    percentageOfAlcoholByVolumeFmcg?: string
    isTradeItemGeneticallyModifiedFmcg?: string
    isTradeItemMarkedAsRecyclable?: string
    sustainability?: string
    approvedVendors?: string
    gpcDefinition?: string
    gpcName?: string
    quantityOfNextLowerLevelTradeItem?: string
    purchasingConversionFactor?: string
    convFctr?: string
    starCategoryIntermediate?: string
    starCategoryMajor?: string
    readyToEatProductIndicator?: string
    readyToEatTemperatureCheckRequiredIndicator?: string
    classOfDangerousGoods?: string
    storageCode?: string
    storageCodeDescription?: string