#%RAML 1.0 DocumentationItem
title: pim-product API Details
content: |
  Product API, is rest service that receives the product information from Pim Enable and publish to Tibco queue,which eventually update the Prism system.